---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: tekton-alert
  namespace: flux-system
spec:
  providerRef:
    name: tekton-provider
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
