---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gamma-scan
  namespace: tekton-runtime
spec:
  params:
    - name: repository
      type: string
    - name: revision
      type: string
    - name: namespace
      type: string
  workspaces:
    - name: source-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: flux-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: namespace
          value: $(params.namespace)
    - name: checkov-scan
      runAfter:
        - fetch-repository
      taskRef:
        name: checkov-scan
      workspaces:
        - name: source
          workspace: source-workspace
      params:
        - name: target-directory
          value: /examples/gitops-kubernetes-application-pipeline
  